[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.105", features = ["serde"] }
serde-wasm-bindgen = "0.6.5"
serde.workspace = true
postcard.workspace = true

game = { path = "../game" }
