[package]
name = "actor"
version = "0.1.0"
edition = "2024"

[dependencies]
ts-rs.workspace = true
serde.workspace = true
kanal.workspace = true
uuid.workspace = true
arrayvec.workspace = true
tokio.workspace = true
